[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "json"
language-servers = ["biome"]
auto-format = true

[[language]]
name = "jsonc"
language-servers = ["biome"]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome"
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome"
]
auto-format = true
roots = ["biome.json", "biome.jsonc", "package.json"]

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true

[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver",]
